steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/slventures-web:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/slventures-web:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/slventures-web:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/slventures-web:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'slventures-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/slventures-web:latest'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'GOOGLE_WORKSPACE_SUBJECT=jsong@seattlepartners.us,GOOGLE_CALENDAR_ID=jsong@seattlepartners.us'
      - '--set-secrets'
      - 'GOOGLE_SERVICE_ACCOUNT_JSON=projects/515955071466/secrets/service-account-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/slventures-web:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/slventures-web:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

